version: '3.8'

services:
    discord-bot:
        build: .
        container_name: vtc
        restart: unless-stopped
        environment:
            - TOKEN=
            - GUILD_ID=
            - RUST_LOG=info
        volumes:
            - ./data:/app/data
